import {StyleSheet, Dimensions} from 'react-native';
export default StyleSheet.create({
  // height100: {
  //   height: '100%',
  // },
  // row: {
  //   flexDirection: 'row',
  // },
  // containerHearder: {
  //   backgroundColor: '#1c5eba',
  //   paddingTop: 10,
  //   opacity: 0.8,
  //   width: '100%',
  //   height: '12%',

  //   shadowOffset: {
  //     height: null,
  //     width: null,
  //   },
  //   shadowRadius: 4,
  //   shadowOpacity: 0.8,
  //   borderBottomColor: '#000000',
  // },
  // ViewSub: {
  //   width: 381,
  //   height: 43,
  //   alignSelf: 'center',
  //   marginTop: 10,
  //   opacity: 0.5,
  //   backgroundColor: '#FFFFFF',
  //   borderRadius: 8,
  // },
  // Search: {
  //   flexDirection: 'row-reverse',
  //   borderRadius: 8,
  // },
  // flex1: {
  //   flex: 1,
  // },
  // marginLeft20: {
  //   marginLeft: 20,
  // },
  // viewSub2: {
  //   flexDirection: 'row',
  //   marginTop: 20,
  //   marginHorizontal: 10,
  // },
  // textsub1: {
  //   fontSize: 23,
  //   color: '#FFFFFF',
  //   marginRight: 10,
  // },
  // TextSub12: {
  //   fontSize: 23,
  //   color: '#20416e',
  // },
  // waitingPill: {
  //   width: 80,
  //   height: 26,
  //   backgroundColor: '#94adbd',
  //   alignItems: 'center',
  //   shadowColor: '#000000',
  //   borderRadius: 40,
  //   shadowOffset: {
  //     height: 1,
  //     width: 1,
  //   },
  //   shadowRadius: 2,
  //   shadowOpacity: 0.4,
  // },

  // pendingPill: {
  //   width: 80,
  //   height: 26,
  //   backgroundColor: '#ff9800',
  //   alignItems: 'center',
  //   shadowColor: '#000000',
  //   borderRadius: 40,
  //   shadowOffset: {
  //     height: 1,
  //     width: 1,
  //   },
  //   shadowRadius: 2,
  //   shadowOpacity: 0.4,
  // },
  // completePill: {
  //   width: 88,
  //   height: 26,
  //   backgroundColor: '#4caf50',
  //   alignItems: 'center',
  //   shadowColor: '#000000',
  //   borderRadius: 40,
  //   shadowOffset: {
  //     height: 1,
  //     width: 1,
  //   },
  //   shadowRadius: 2,
  //   shadowOpacity: 0.4,
  // },
  // viewSub4: {
  //   flex: 1,
  //   flexDirection: 'row-reverse',
  // },
  // viewSub5: {
  //   marginTop: 20,
  // },

  // viewSub6: {
  //   width: 88,
  //   height: 26,
  //   backgroundColor: '#c2c2c2',
  //   alignItems: 'center',
  //   shadowColor: '#000000',
  //   borderRadius: 13,
  //   marginTop: 1,
  // },
  // viewSub8: {
  //   width: 88,
  //   height: 26,
  //   backgroundColor: '#ff9800',
  //   alignItems: 'center',
  //   shadowColor: '#000000',
  //   borderRadius: 13,
  //   marginTop: 1,
  // },
  // viewSub9: {
  //   width: 88,
  //   height: 26,
  //   backgroundColor: '#4caf50',
  //   alignItems: 'center',
  //   shadowColor: '#000000',
  //   borderRadius: 13,
  //   marginTop: 1,
  // },
  // flexDirection: {
  //   flexDirection: 'row',
  // },
  // ImageProgress: {
  //   alignSelf: 'center',
  //   height: 84,
  //   width: 395,
  //   marginTop: 10,
  //   borderRadius: 10,
  //   flexDirection: 'row',
  // },
  // textProgress: {
  //   fontSize: 25,
  //   color: '#ff9800',
  // },
  // textProgress2: {
  //   fontSize: 50,
  //   color: '#d1d1d1',
  // },
  // textProgress25: {
  //   fontSize: 50,
  //   color: '#ff9800',
  // },
  // backgroundView: {
  //   height: Dimensions.get('window').height * 0.2,
  //   width: '100%',
  //   flex: 1,
  //   resizeMode: 'cover',
  //   backgroundColor: '#FFFFFF',
  //   borderBottomColor: 'transparent',
  // },
  // HeaderView: {
  //   backgroundColor: 'transparent',
  //   paddingTop: 0,
  //   // height: 72,
  //   // width: 414,
  //   borderBottomColor: 'transparent',
  // },
  // TouchViewBox1: {
  //   marginTop: 20,
  //   flexDirection: 'row',
  //   justifyContent: 'center',
  //   width: Dimensions.get('window').width * 0.92,
  //   alignSelf: 'center',
  // },
  // TouchViewBox2: {
  //   marginTop: 10,
  //   flexDirection: 'row',
  //   justifyContent: 'center',
  //   width: Dimensions.get('window').width * 0.92,
  //   alignSelf: 'center',
  // },
  // ViewBox: {
  //   flexDirection: 'row',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  //   alignContent: 'center',
  //   alignItems: 'center',
  //   borderRadius: 5,
  // },
  // DropDownHaed2: {
  //   width: Dimensions.get('window').width * 0.93,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   alignSelf: 'center',
  //   paddingHorizontal: 15,
  //   paddingVertical: 7,
  //   borderTopLeftRadius: 5,
  //   borderTopRightRadius: 5,
  //   // marginTop: -10,
  // },
  // shadow4: {
  //   backgroundColor: 'white',
  //   shadowColor: '#ccc',
  //   shadowOffset: {
  //     width: 0,
  //     height: 1,
  //   },
  //   shadowOpacity: 0.5,
  //   shadowRadius: 3,
  //   elevation: 2,
  // },
  // TextSub123: {
  //   color: '#20416e',
  //   fontSize: 22,
  //   marginTop: 6,
  // },
  // Line: {
  //   borderWidth: 0.5,
  //   borderColor: '#e2e2e2',
  //   margin: 10,
  // },
  // ViewIcon: {
  //   flex: 1,
  //   flexDirection: 'row',
  //   alignItems: 'center',
  // },
  // flexRow: {
  //   flexDirection: 'row',
  // },
  // textUser: {
  //   fontSize: 20,
  //   color: '#4b4b4b',
  // },
  // IconUser: {
  //   marginLeft: 10,
  //   color: '#5D6D7E',
  // },
  // ViewBox1: {
  //   width: Dimensions.get('window').width * 0.93,
  //   height: null,
  //   backgroundColor: '#FFFFFF',
  //   alignSelf: 'center',
  //   borderBottomLeftRadius: 5,
  //   borderBottomRightRadius: 5,
  //   marginBottom: 10,
  //   paddingBottom: 10,
  // },
  // ViewBox3: {
  //   width: Dimensions.get('window').width * 0.93,
  //   height: null,
  //   backgroundColor: '#FFFFFF',
  //   alignSelf: 'center',
  //   borderBottomLeftRadius: 5,
  //   borderBottomRightRadius: 5,
  // },
  // ViewBox4: {
  //   width: Dimensions.get('window').width * 0.93,
  //   height: null,
  //   backgroundColor: '#FFFFFF',
  //   alignSelf: 'center',
  //   borderBottomLeftRadius: 5,
  //   borderBottomRightRadius: 5,
  // },
  // ViewBox5: {
  //   width: Dimensions.get('window').width * 0.93,
  //   height: null,
  //   backgroundColor: '#FFFFFF',
  //   alignSelf: 'center',

  //   borderBottomLeftRadius: 5,
  //   borderBottomRightRadius: 5,
  // },
  // viewAlert: {
  //   backgroundColor: '#dadada',
  //   width: 381,
  //   height: 51,
  //   alignSelf: 'center',
  //   flexDirection: 'row',
  //   justifyContent: 'center',
  //   alignContent: 'center',
  //   alignItems: 'center',
  //   marginBottom: 10,
  //   borderRadius: 8,
  // },
  // viewAccept: {
  //   backgroundColor: '#23a735',
  //   width: '95%',
  //   height: 51,
  //   alignSelf: 'center',
  //   flexDirection: 'row',
  //   justifyContent: 'flex-start',
  //   alignContent: 'center',
  //   alignItems: 'center',
  //   marginBottom: 10,
  //   borderRadius: 8,
  // },
  // textAlert: {
  //   fontSize: 22,
  //   color: '#9a9a9a',
  // },
  // textAccept: {
  //   fontSize: 22,
  //   color: '#FFFFFF',
  // },
  // backgroundAppel: {
  //   alignSelf: 'center',
  //   height: null,
  //   width: Dimensions.get('window').width * 0.95,
  //   marginTop: 10,
  //   borderRadius: 10,
  //   flexDirection: 'row',
  //   padding: 10,
  //   paddingHorizontal: 15,
  // },
  // itemStyle: {
  //   borderWidth: 2,
  // },
  // checkmarkImage: {
  //   width: 39,
  //   height: 39,
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  //   alignItems: 'center',
  //   marginHorizontal: 14,
  // },
  // alertContainer: {
  //   flexDirection: 'row',
  //   alignSelf: 'center',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   width: '95%',
  //   height: null,
  //   marginBottom: 15,
  // },
  // documentPanel: {
  //   width: '95%',
  //   height: 43,
  //   flexDirection: 'row',
  //   backgroundColor: '#f3f3f3',
  //   alignItems: 'center',
  //   alignSelf: 'center',
  //   justifyContent: 'flex-start',
  //   borderRadius: 8,
  //   marginBottom: 20,
  // },
  // smallIcon: {
  //   marginHorizontal: 10,
  //   alignItems: 'center',
  // },
  // detailHeadLabel: {
  //   flex: 0.7,
  //   fontSize: 20,
  //   color: '#20416e',
  //   marginLeft: 10,
  // },
  // detailLabel: {
  //   flex: 1,
  //   marginRight: 10,
  // },
  // searchContainer: {
  //   width: Dimensions.get('window').width * 0.95,
  //   alignSelf: 'center',
  // },
  // searchBackground: {
  //   width: '100%',
  //   height: 43,
  //   alignSelf: 'center',
  //   marginTop: 10,
  //   borderRadius: 8,
  // },
  // searchBar: {
  //   backgroundColor: null,
  //   flexDirection: 'row-reverse',
  //   elevation: 0, // disable android shadow
  // },
  // reportCard: {
  //   borderRadius: 10,
  // },
  // reportCardTitle: {
  //   flex: 1,
  //   alignSelf: 'flex-start',
  //   marginHorizontal: 10,
  // },
  // reportCardLabel: {
  //   fontSize: 16,
  //   color: '#20416e',
  //   marginRight: 5,
  // },
  // reportCardCalender: {
  //   width: 16,
  //   height: 16,
  //   marginRight: 5,
  // },

  // footer: {
  //   padding: 10,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   flexDirection: 'row',
  // },
  // basketIconContainer: {
  //   width: 30,
  // },

  height100: {
    flex: 1,
  },
  row: {
    flexDirection: 'row',
  },
  containerHearder: {
    backgroundColor: '#1c5eba',
    paddingTop: 10,
    opacity: 0.8,
    width: '100%',
    height: '12%',

    shadowOffset: {
      height: null,
      width: null,
    },
    shadowRadius: 4,
    shadowOpacity: 0.8,
    borderBottomColor: '#000000',
  },
  ViewSub: {
    width: 381,
    height: 43,
    alignSelf: 'center',
    marginTop: 10,
    opacity: 0.5,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
  },
  Search: {
    flexDirection: 'row-reverse',
    borderRadius: 8,
  },
  flex1: {
    flex: 1,
  },
  marginLeft20: {
    marginLeft: 20,
  },
  viewSub2: {
    flexDirection: 'row',
    marginTop: 20,
    marginHorizontal: 10,
  },
  textsub1: {
    fontSize: 23,
    color: '#FFFFFF',
    marginRight: 10,
  },
  TextSub12: {
    fontSize: 23,
    color: '#20416e',
  },
  waitingPill: {
    width: 80,
    height: 26,
    backgroundColor: '#94adbd',
    alignItems: 'center',
    shadowColor: '#000000',
    borderRadius: 40,
    shadowOffset: {
      height: 1,
      width: 1,
    },
    shadowRadius: 2,
    shadowOpacity: 0.4,
  },
  pendingPill: {
    width: 80,
    height: 26,
    backgroundColor: '#ff9800',
    alignItems: 'center',
    shadowColor: '#000000',
    borderRadius: 40,
    shadowOffset: {
      height: 1,
      width: 1,
    },
    shadowRadius: 2,
    shadowOpacity: 0.4,
  },
  completePill: {
    width: 88,
    height: 26,
    backgroundColor: '#4caf50',
    alignItems: 'center',
    shadowColor: '#000000',
    borderRadius: 40,
    shadowOffset: {
      height: 1,
      width: 1,
    },
    shadowRadius: 2,
    shadowOpacity: 0.4,
  },
  viewSub4: {
    flex: 1,
    flexDirection: 'row-reverse',
  },
  viewSub5: {
    marginTop: 20,
  },

  viewSub6: {
    width: 88,
    height: 26,
    backgroundColor: '#c2c2c2',
    alignItems: 'center',
    shadowColor: '#000000',
    borderRadius: 13,
    marginTop: 1,
  },
  viewSub8: {
    width: 88,
    height: 26,
    backgroundColor: '#ff9800',
    alignItems: 'center',
    shadowColor: '#000000',
    borderRadius: 13,
    marginTop: 1,
  },
  viewSub9: {
    width: 88,
    height: 26,
    backgroundColor: '#4caf50',
    alignItems: 'center',
    shadowColor: '#000000',
    borderRadius: 13,
    marginTop: 1,
  },
  flexDirection: {
    flexDirection: 'row',
  },
  ImageProgress: {
    alignSelf: 'center',
    height: 84,
    width: 395,
    marginTop: 10,
    borderRadius: 10,
    flexDirection: 'row',
  },
  textProgress: {
    fontSize: 25,
    color: '#ff9800',
  },
  textProgress2: {
    fontSize: 50,
    color: '#d1d1d1',
  },
  textProgress25: {
    fontSize: 50,
    color: '#ff9800',
  },
  backgroundView: {
    height: Dimensions.get('window').height * 0.2,
    width: '100%',
    flex: 1,
    resizeMode: 'cover',
    backgroundColor: '#FFFFFF',
    borderBottomColor: 'transparent',
  },
  HeaderView: {
    backgroundColor: 'transparent',
    paddingTop: 0,
    // height: 72,
    // width: 414,
    borderBottomColor: 'transparent',
  },
  TouchViewBox1: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    width: Dimensions.get('window').width * 0.92,
    alignSelf: 'center',
  },
  TouchViewBox2: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    width: Dimensions.get('window').width * 0.92,
    alignSelf: 'center',
  },
  ViewBox: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
    alignContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  DropDownHaed2: {
    width: Dimensions.get('window').width * 0.93,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    paddingHorizontal: 15,
    paddingVertical: 7,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    // marginTop: -10,
  },
  shadow4: {
    backgroundColor: 'white',
    shadowColor: '#ccc',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.5,
    shadowRadius: 3,
    elevation: 2,
  },
  TextSub123: {
    color: '#20416e',
    fontSize: 22,
    marginTop: 6,
  },
  Line: {
    borderWidth: 0.5,
    borderColor: '#e2e2e2',
    margin: 10,
    marginTop: 0,
  },
  ViewIcon: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  flexRow: {
    flexDirection: 'row',
  },
  textUser: {
    fontSize: 20,
    color: '#4b4b4b',
  },
  IconUser: {
    marginLeft: 10,
    color: '#5D6D7E',
  },
  ViewBox1: {
    width: Dimensions.get('window').width * 0.93,
    height: null,
    backgroundColor: '#FFFFFF',
    alignSelf: 'center',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    marginBottom: 10,
    paddingBottom: 10,
  },
  ViewBox3: {
    width: Dimensions.get('window').width * 0.93,
    height: null,
    backgroundColor: '#FFFFFF',
    alignSelf: 'center',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  ViewBox4: {
    width: Dimensions.get('window').width * 0.93,
    height: null,
    backgroundColor: '#FFFFFF',
    alignSelf: 'center',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  ViewBox5: {
    width: Dimensions.get('window').width * 0.93,
    height: null,
    backgroundColor: '#FFFFFF',
    alignSelf: 'center',

    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  viewAlert: {
    backgroundColor: '#dadada',
    width: '95%',
    height: 51,
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    borderRadius: 8,
  },
  viewAccept: {
    backgroundColor: '#23a735',
    width: '95%',
    height: 51,
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    borderRadius: 8,
  },
  textAlert: {
    fontSize: 22,
    color: '#9a9a9a',
  },
  textAccept: {
    fontSize: 22,
    color: '#FFFFFF',
  },
  backgroundAppel: {
    alignSelf: 'center',
    height: null,
    width: Dimensions.get('window').width * 0.95,
    marginTop: 10,
    borderRadius: 10,
    flexDirection: 'row',
    padding: 10,
  },
  itemStyle: {
    borderWidth: 2,
  },
  checkmarkImage: {
    width: 39,
    height: 39,
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    marginHorizontal: 14,
  },
  alertContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    width: '95%',
    height: null,
    marginBottom: 15,
  },
  documentPanel: {
    width: '95%',
    height: 43,
    flexDirection: 'row',
    backgroundColor: '#f3f3f3',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'flex-start',
    borderRadius: 8,
    marginBottom: 20,
  },
  smallIcon: {
    marginHorizontal: 10,
    alignItems: 'center',
  },
  detailHeadLabel: {
    flex: 0.7,
    fontSize: 20,
    color: '#20416e',
    marginLeft: 10,
  },
  detailLabel: {
    flex: 1,
    marginRight: 10,
  },
  searchContainer: {
    width: Dimensions.get('window').width * 0.95,
    alignSelf: 'center',
  },
  searchBackground: {
    width: '100%',
    height: 43,
    alignSelf: 'center',
    marginTop: 10,
    borderRadius: 8,
  },
  searchBar: {
    backgroundColor: null,
    flexDirection: 'row-reverse',
    elevation: 0, // disable android shadow
  },
  reportCard: {
    borderRadius: 10,
  },
  reportCardTitle: {
    flex: 1,
    alignSelf: 'flex-start',
    marginHorizontal: 10,
  },
  reportCardLabel: {
    fontSize: 16,
    color: '#20416e',
    marginRight: 5,
  },
  reportCardCalender: {
    width: 16,
    height: 16,
    marginRight: 5,
  },
  footer: {
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  basketIconContainer: {
    width: 30,
  },
});
