import {StyleSheet, Dimensions, Platform} from 'react-native';
import { ViewScale } from '../../config/ViewScale';
const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;
const width1 = Dimensions.get('screen').width;
const height1 = Dimensions.get('screen').height;
export default StyleSheet.create({
  ViewSelec: {
    width: '50%',
    flexDirection: 'row',
    backgroundColor: 'red',
    // justifyContent: 'center',
    // alignContent: 'center',
    // alignSelf: 'center',
  },
  SafeArea: {
    backgroundColor: '#FFFFFF',
    flex: 1,
  },
  Container: {
    width: '75%',
    height: ViewScale(70),
  },
  ContainerAndroid: {
    width: '85%',
    height: ViewScale(70),
  },
  backgroundColor: {
    backgroundColor: '#f4f5f8',
  },
  fontSelec: {
    fontSize: ViewScale(15),
    color: '#2d6dc4',
  },
  fontSelecP: {
    fontSize: ViewScale(15),
    color: '#40536d',
    // textAlign: 'center',
    // left: Dimensions.get('window').width < 400 ? '-50%' : 0,
  },
  StyeSelec: {
    backgroundColor: null,
    borderColor: 'transparent',
    paddingVertical: ViewScale(10),
  },
  ArrowStyle: {
    backgroundColor: 'transparent',
  },
  item: {
    flexDirection: 'column',
  },
  flewRow: {
    flexDirection: 'row',
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: ViewScale(30),
    zIndex: 0,
  },
  ViewFlatList1: {
    borderBottomColor: '#c1d0dc',
    borderBottomWidth: 1,
    width: width * 0.97,
    alignContent: 'center',
    height: null,
  },
  ViewFlatList2: {
    borderBottomColor: '#c1d0dc',
    borderBottomWidth: 1,
    width: ViewScale(380),
    alignContent: 'center',
    height: null,
  },
  ViewFlatList3: {
    flex: 1.3,
    height: null,
    marginLeft: ViewScale(10),
  },
  ViewFlatList4: {
    marginTop: ViewScale(9),
    // marginBottom: 13,
    flexDirection: 'row',
  },
  fontFlatList: {
    fontSize: ViewScale(24),
    color: '#014886',
    fontWeight: 'normal',
    fontFamily: 'Kittithada Bold 75',
  },
  fontFlatListIos: {
    fontSize: ViewScale(23),
    color: '#014886',
    fontFamily: 'Kittithada Bold 75',
  },
  fontFlatList2: {
    fontSize: ViewScale(18),
    color: '#73838f',
    flex: 0.9,
    fontFamily: 'Kittithada Bold 75',
  },
  fontFlatList3: {
    fontSize: ViewScale(18),
    color: '#73838f',
  },
  ViewFlatList5: {
    alignSelf: 'center',
    flexDirection: 'row-reverse',
    flex: 0.4,
    alignItems: 'center',
  },
  marginLeft10: {
    // marginLeft: 10,
  },
  animatedBox: {
    flex: 1,
    backgroundColor: '#38C8EC',
    padding: ViewScale(10),
  },
  body: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f4f5f8',
  },
  ViewSub1: {
    alignItems: 'center',
    flexDirection: 'row',
    // alignSelf: 'center',
    // backgroundColor: 'red',
  },
  ViewSub2: {
    // flex: 1,
    // marginLeft: 10,
    // marginRight: 35,
    // flexDirection: 'row',
    flex: 1,
  },
  TextHear: {
    fontSize: ViewScale(28),
    color: '#2d6dc4',
    left: ViewScale(15),
  },
  flexDirection: {
    flexDirection: 'row-reverse',
  },
  ViewTabSearch: {
    justifyContent: 'center',
    //zIndex: 0,
  },
  TouchSearch: {
    flexDirection: 'row',
    alignSelf: 'center',
    marginLeft: ViewScale(10),
  },
  fontSearch: {
    fontSize: ViewScale(15),
    color: '#40536d',
  },
  ViewImgSearch: {
    alignSelf: 'center',
    marginLeft: ViewScale(5),
  },
  ViewTab: {
    width: '95%',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  TabStyle: {
    backgroundColor: '#ebf3f7',
    width: null,
    height: null,
    // borderColor: 'transparent',
    borderTopRightRadius: ViewScale(13),
    borderTopLeftRadius: ViewScale(13),
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderWidth: 2,
    borderColor: '#ebf3f7',
    paddingVertical: ViewScale(3),
    // borderTopLeftRadius:10,
    // borderTopRightRadius:10
    // borderWidth:1

    // borderWidth: 1,
    // borderRadius: 5,
    // borderColor: 'red',
    // borderBottomWidth: 0,
    shadowColor: '#c2cedf',
    shadowOffset: {width: 0, height: 1.8},
    shadowOpacity: 0.9,

    elevation: 1,
  },
  TabText: {
    color: '#73838f',
    fontSize: ViewScale(20),
    fontFamily: 'PSL Kittithada Pro',
    textAlign: 'center',
    lineHeight: ViewScale(23),
    marginTop: ViewScale(4),
  },
  fistTabStyle: {
    // borderTopRightRadius: 13,
    // borderTopLeftRadius: 13,
    borderRightWidth: 1,
    borderLeftWidth: 1,
    // borderWidth: 1,
    // borderColor: '#2d6dc4',
  },
  lastTabStyle: {
    // borderTopRightRadius: 13,
    // borderTopLeftRadius: 13,
    borderRightWidth: 1,
    // borderLeftWidth: 1,
    // borderWidth: 1,
    // borderColor: '#2d6dc4',
  },
  backgroundTab: {
    // borderTopColor: '#00000050',
    // borderTopWidth: 8,
    backgroundColor: '#2d6dc4',
  },
  Tabcontainer: {
    width: ViewScale(381),
    height: null,
    alignSelf: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    borderRadius: ViewScale(10),
  },
  ViewTab2: {
    justifyContent: 'center',
    // borderColor: '#f4f5f8',
    // borderTopWidth: 14,
    flexDirection: 'row',
    elevation: ViewScale(10),
    // width: null,
    // height: 50,
    marginBottom: ViewScale(20),
    marginTop: 0,
  },
  Tabcontainer2: {
    width: ViewScale(381),
    height: '100%',
    alignSelf: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
  },
  TocuhView: {
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    width: ViewScale(384),
    height: ViewScale(50),
    borderWidth: ViewScale(10),
    borderColor: '#f4f5f850',
  },

  //SearchMENU

  flex1: {
    flex: 1,
  },
  textHearder: {
    color: '#20416e',
    fontSize: ViewScale(25),
    // fontWeight: 'bold',
  },
  ViewTabClose: {
    alignSelf: 'center',
    marginLeft: ViewScale(5),
  },
  containerSearch: {
    backgroundColor: '#f4f5f8',
    shadowColor: '#000000',
    shadowOffset: {
      height: 0,
      width: 9,
    },
    shadowRadius: 4,
    shadowOpacity: 0.4,
  },
  ViewSubSearch1: {
    marginTop: ViewScale(20),
    paddingHorizontal: ViewScale(15),
    // marginLeft: 20,
    flex: 1,
  },
  textYear: {
    fontSize: ViewScale(24),
    // fontWeight: 'bold',
    color: '#20416e',
  },
  ViewSearYear: {
    borderRadius: ViewScale(18),
    width: ViewScale(288),
    height: ViewScale(33),
    borderWidth: 1,
    borderColor: '#dadada',
    flexDirection: 'row',
    alignContent: 'center',
    alignItems: 'center',
  },
  ViewSearYear2: {
    borderRadius: ViewScale(18),
    width: ViewScale(288),
    height: ViewScale(33),
    borderWidth: 1,
    borderColor: '#2d6dc4',
    flexDirection: 'row',
    alignContent: 'center',
    alignItems: 'center',
  },
  ViewIconYear: {
    marginLeft: ViewScale(10),
    marginTop: ViewScale(5),
    marginRight: ViewScale(5),
  },
  textInputYear: {
    fontSize: ViewScale(22),
    color: '#dadada',
  },
  textInputYear2: {
    fontSize: ViewScale(22),
    color: '#3c3c3c',
  },
  ViewLine: {
    paddingTop: ViewScale(20),
  },
  ViewCountry: {
    paddingTop: ViewScale(10),
  },
  TextCountry: {
    fontSize: ViewScale(23),
    // fontWeight: 'bold',
    color: '#20416e',
    textAlign: 'left',
  },
  TextProducts: {
    fontSize: ViewScale(24),
    // fontWeight: 'bold',
    color: '#20416e',
  },
  ViewSubSearch2: {
    borderRadius: ViewScale(18),
    width: ViewScale(288),
    height: ViewScale(33),
    borderWidth: 1,
    borderColor: '#2d6dc4',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },
  ViewSubSearch8: {
    borderRadius: ViewScale(18),
    width: ViewScale(288),
    height: ViewScale(33),
    borderWidth: 1,
    borderColor: '#dadada',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },
  ViewSubSearch22: {
    borderRadius: ViewScale(18),
    width: ViewScale(300),
    height: ViewScale(33),
    borderWidth: 1,
    borderColor: '#2d6dc4',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },

  ViewSubSearch88: {
    borderRadius: ViewScale(18),
    width: '100%',
    height: ViewScale(33),
    borderWidth: 1,
    borderColor: '#dadada',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },

  ViewSubSearch3: {
    marginTop: ViewScale(5),
    marginLeft: ViewScale(10),
    backgroundColor: 'transparent',
  },
  ViewSubSearch4: {
    backgroundColor: '#f4f5f8',
    flexDirection: 'row',
    alignItems: 'center',
  },
  ViewSubSearch5: {
    flexDirection: 'row',
    alignItems: 'center',
    // marginLeft: -20,
  },
  TouchDelete: {
    width: ViewScale(70),
    height: ViewScale(34),
    borderRadius: ViewScale(24.5),
    // backgroundColor: '#f96145',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 0,
  },
  TouchAccept: {
    width: ViewScale(70),
    height: ViewScale(34),
    borderRadius: ViewScale(24.5),
    // backgroundColor: '#2d6dc4',
    alignItems: 'center',
    justifyContent: 'center',
    margin: ViewScale(10),
  },
  TextTouchDelete: {
    color: '#FFFFFF',
    fontSize: ViewScale(18),
  },
  TextTouchAccept: {
    color: '#FFFFFF',
    fontSize: ViewScale(18),
  },
  containerCheck: {
    backgroundColor: '#f4f5f8',
    borderColor: '#f4f5f8',
  },
  textCheck: {
    fontSize: ViewScale(16),
    color: '#20416e',
  },
  ImageSeach: {
    width: ViewScale(24),
    height: ViewScale(24),
    backgroundColor: 'transparent',
    marginLeft: ViewScale(10),
    top: ViewScale(3),
  },
  TextInputSeach: {
    width: '100%',
    fontSize: ViewScale(20),
    color: '#000000',
    marginLeft: ViewScale(10),
    padding: 0,
    backgroundColor: 'transparent',
    top: Platform.OS === 'android' ? 1 : 0,
  },
  ViewSeach1: {
    width: width1 * 0.9,
    height: Platform.OS === 'android' ? height * 0.06 : height * 0.66,
    // borderRadius: 18,
    // borderWidth: 1,
    // borderColor: '#dadada',
    // flexDirection: 'row',
    // alignItems: 'center',
    // backgroundColor: 'transparent',
  },
  ViewSeachF: {
    width: '90%',
    height: ViewScale(33),
    borderRadius: ViewScale(18),
    borderWidth: 1,
    borderColor: '#dadada',
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: 'transparent',
    marginHorizontal: ViewScale(20),

    // top:15
  },

  ViewSeach: {
    width: '90%',
    height: ViewScale(33),
    borderRadius: ViewScale(18),
    borderWidth: 1,
    borderColor: '#dadada',
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: 'transparent',
    marginHorizontal: ViewScale(20),
    marginBottom: ViewScale(10),
    // top:15
  },
  ViewSeachcontry: {
    width: '90%',
    height: ViewScale(33),
    borderRadius: ViewScale(18),
    borderWidth: 1,
    borderColor: '#dadada',
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: 'transparent',
    marginHorizontal: ViewScale(20),

    backgroundColor: '#FFFFFF',
  },
  separator: {
    height: ViewScale(0.5),
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  footer: {
    padding: ViewScale(10),
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  basketIconContainer: {
    // width: 30,
    // borderWidth:1
  },
  AndroidTab: {
    // shadowColor: '#000',
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowOpacity: 0.25,
    // shadowRadius: 3.84,
    // // borderColor: 'transparent',
    // borderRadius: 3.84,
    // elevation: 5,
    width: '100%',
    height: ViewScale(42),
  },
  tabContainer: {
    // shadowColor: '#000',
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowOpacity: 0.4,
    // shadowRadius: 3.84,

    // elevation: 5,
    width: '100%',
    height: null,
  },
  OverlayHight1: {
    height: ViewScale(100),
  },
  OverlayHight2: {
    height: ViewScale(100),
  },
  OverlayHight3: {
    height: ViewScale(120),
  },
  OverlayView2: {
    width: width1 - 50,
    height: null,
  },
  choosetime: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#2d6dc4',
    backgroundColor: '#2d6dc4',
    borderRadius: ViewScale(8),
    height: ViewScale(35),
  },

  choosetime1: {
    zIndex: -1,
    flex: 1,
    // paddingHorizontal: 5,
    borderWidth: 0.5,
    borderColor: '#FFFFFF',
    backgroundColor: '#FFFFFF',
    height: ViewScale(35),
    paddingHorizontal: ViewScale(10),
    marginHorizontal: ViewScale(3),
    borderRadius: ViewScale(17),
    borderColor: '#2d6dc4',
    borderWidth: 1,
  },
  choosecontry: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#04a68a',
    backgroundColor: '#04a68a',
    borderRadius: ViewScale(8),
    height: ViewScale(35),
  },  
  chooseproducts: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#568ae0',
    backgroundColor: '#568ae0',
    borderRadius: ViewScale(8),
    height: ViewScale(35),
  },  

  Viewin1: {justifyContent: 'center', flex: 1},
  Viewin2:{justifyContent: 'center',flex:0.2},
  ViewTextin:{
    color: '#FFFFFF',
    fontSize: ViewScale(20),
    textAlign: 'center',
  }
});
