import { StyleSheet, Dimensions, Platform } from 'react-native';
export const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  backgroundView: {
    // height: Dimensions.get('window').height * 0.2,
    // width: '100%',
    flex: 1,
    // resizeMode: 'cover',
    backgroundColor: '#FFFFFF',
    borderBottomColor: 'transparent',
  },
  HeaderView: {
    backgroundColor: 'transparent',
    paddingTop: 0,
    // height: 72,
    // width: 414,
    borderBottomColor: 'transparent',
  },
  flex1: {
    flex: 1,
  },
  row: {
    flexDirection: 'row',
  },
  View1: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    width: Dimensions.get('window').width * 0.93,
    height: 40,
    marginVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 5,
    backgroundColor: '#fff',
  },
  dateText: {
    flex: 1,
    color: '#20416e',
    fontSize: 22,
  },
  ViewSubHeader: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    width: Dimensions.get('window').width * 0.93,
    height: null,
    alignSelf: 'center',
  },
  textHearder1: {
    color: '#20416e',
    marginTop: 10,
    paddingHorizontal: 10,
    fontSize: 24,
  },
  ViewTap: {
    marginTop: 10,
    alignContent: 'center',
    // backgroundColor: '#2d6dc4',
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  dropdownGradient: {
    width: Dimensions.get('window').width * 0.8,
    height: 38,
    alignSelf: 'center',
    justifyContent: 'center',
    alignContent: 'center',
    borderRadius: 10,
  },
  dropdownIcon: {
    marginRight: Platform.OS === 'android' ? 20:15,
    top: Platform.OS === 'android' ? 1 : 1,
    left: 15
  },
  dropdownIcon2: {
    marginRight: 20,
    top: Platform.OS === 'android' ? 16 : 3,
    left: 10
  },
  ViewSubHeader2: {
    marginTop: 10,
    borderRadius: 10,
    width: '90%',
    height: null,
    alignSelf: 'center',
    borderColor: '#ddd',
    borderWidth: 1,
    marginBottom: 20,
  },
  textHearder2: {
    fontSize: 22,
    color: '#20416e',
    //fontWeight: 'bold',
  },
  Viewcheckbox: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FFFFFF',
  },
  checkboxText: {
    fontSize: 20,
    fontFamily: 'PSL Kittithada Pro',
    fontWeight: 'normal',
  },
  checkIcon: {
    borderWidth: 1,
    width: 20,
    height: 20,
    borderRadius: 10,
    borderColor: '#cfcfcf',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ViewBTN: {
    flex: 1,
    marginTop: 30,
    marginBottom: 30,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    // position: 'absolute',
  },
  BTN1: {
    width: Dimensions.get('window').width * 0.85,
    height: 48,
    backgroundColor: '#f96145',
    alignContent: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  BTN2: {
    flex: 1,
    height: 48,
    alignContent: 'center',
    justifyContent: 'center',
    marginHorizontal: 10,
    marginVertical: 10,
    borderRadius: 10,
    backgroundColor: '#f96145',
  },
  BTN3: {
    flex: 1,
    height: 48,
    alignContent: 'center',
    justifyContent: 'center',
    marginHorizontal: 10,
    marginVertical: 10,
    borderRadius: 10,
    backgroundColor: '#2d6dc4',
  },
  BTNText: {
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
    fontSize: 25,
    color: '#FFFFFF',
  },
  Viewin: {
    flexDirection: 'row',
  },
  Viewin2: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  TextSupinput: {
    fontSize: 22,
    color: '#20416e',
  },
  TextSupinput2: {
    fontSize: 22,
    color: '#fe2c2c',
  },
  ViewInput: {
    width: Dimensions.get('window').width * 0.8,
    height: 36,
    justifyContent: 'center',
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 21.5,
    borderColor: '#cad8e1',
    backgroundColor: '#FFFFFF',

    shadowColor: '#cad8e1',
    shadowOffset: {
      height: 0,
      width: 9,
    },
    shadowRadius: 4,
    shadowOpacity: 0.4,
  },
  ViewInputRed: {
    width: Dimensions.get('window').width * 0.8,
    height: 36,
    justifyContent: 'center',
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 21.5,
    borderColor: '#B22222',
    backgroundColor: '#FFFFFF',

    shadowColor: '#cad8e1',
    shadowOffset: {
      height: 0,
      width: 9,
    },
    shadowRadius: 4,
    shadowOpacity: 0.4,
  },
  ViewInputRed2: {
    width: Dimensions.get('window').width * 0.8,
    height: 120,
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 21.5,
    borderColor: '#B22222',
    backgroundColor: '#FFFFFF',

    shadowColor: '#cad8e1',
    shadowOffset: {
      height: 0,
      width: 9,
    },
    shadowRadius: 4,
    shadowOpacity: 0.4,
  },
  ViewInput2: {
    width: Dimensions.get('window').width * 0.8,
    height: 120,
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 21.5,
    borderColor: '#cad8e1',
    backgroundColor: '#FFFFFF',

    shadowColor: '#cad8e1',
    shadowOffset: {
      height: 0,
      width: 9,
    },
    shadowRadius: 4,
    shadowOpacity: 0.4,
  },
  ViewInput3: {
    width: Dimensions.get('window').width * 0.8,
    height: 200,
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 21.5,
    borderColor: '#cad8e1',
    backgroundColor: '#FFFFFF',

    shadowColor: '#cad8e1',
    shadowOffset: {
      height: 0,
      width: 9,
    },
    shadowRadius: 4,
    shadowOpacity: 0.4,
  },
  ViewInput4: {
    marginTop: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 21.5,
    // width: '90%',
    // height: 40,
    height: Dimensions.get('window').height * 0.05,
    width: Dimensions.get('window').width * 0.5,
    alignSelf: 'center',
    borderColor: '#cad8e1',
    borderWidth: 1,
    shadowColor: '#cad8e1',
    justifyContent: 'center',

    shadowOffset: {
      height: 0,
      width: 9,
    },
    shadowRadius: 4,
    shadowOpacity: 0.4,
  },
  ViewInput5: {
    flex: 1,
    height: 36,
    justifyContent: 'center',
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 21.5,
    borderColor: '#cad8e1',
    backgroundColor: '#fff',

    shadowColor: '#cad8e1',
    shadowOffset: {
      height: 0,
      width: 9,
    },
    shadowRadius: 4,
    shadowOpacity: 0.4,
  },
  ViewInputRed5: {
    flex: 1,
    height: 36,
    justifyContent: 'center',
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 21.5,
    borderColor: '#B22222',
    backgroundColor: '#fff',

    shadowColor: '#cad8e1',
    shadowOffset: {
      height: 0,
      width: 9,
    },
    shadowRadius: 4,
    shadowOpacity: 0.4,
  },
  ViewInput6: {
    minWidth: 120,
    width: Dimensions.get('window').width * 0.2,
    height: 36,
    justifyContent: 'center',
    marginVertical: 10,
    marginLeft: 10,
    borderWidth: 1,
    borderRadius: 21.5,
    borderColor: '#cad8e1',
    backgroundColor: '#FFFFFF',

    shadowColor: '#cad8e1',
    shadowOffset: {
      height: 0,
      width: 9,
    },
    shadowRadius: 4,
    shadowOpacity: 0.4,
  },
  ViewInputRed6: {
    minWidth: 120,
    width: Dimensions.get('window').width * 0.2,
    height: 36,
    justifyContent: 'center',
    marginVertical: 10,
    marginLeft: 10,
    borderWidth: 1,
    borderRadius: 21.5,
    borderColor: '#B22222',
    backgroundColor: '#FFFFFF',

    shadowColor: '#cad8e1',
    shadowOffset: {
      height: 0,
      width: 9,
    },
    shadowRadius: 4,
    shadowOpacity: 0.4,
  },
  TextInput: {
    fontSize: 22,
    fontWeight: 'normal',
    color: '#4b4b4b',
    marginLeft: 10,
    padding: 0,
  },
  DropDownHaed2: {
    width: Dimensions.get('window').width * 0.93,
    justifyContent: 'center',
    paddingHorizontal: 15,
    paddingVertical: 7,
    alignSelf: 'center',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,

    // marginTop: -10,
  },
  shadow4: {
    backgroundColor: 'white',
    shadowColor: '#ccc',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.5,
    shadowRadius: 3,
    elevation: 0,
  },
  flexRow: {
    flexDirection: 'row',
  },
  TextSub12: {
    color: '#20416e',
    fontSize: 22,
  },
  marginLeft10: {
    marginLeft: 10,
  },
  alignCenter: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  justifyCenter: {
    justifyContent: 'center',
  },
  selfCenter: {
    alignSelf: 'center',
  },
  ViewNone: {
    display: 'none',
  },
  TouchViewBox1: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: Dimensions.get('window').width * 0.93,
    alignSelf: 'center',
  },
  ViewBox: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
    alignContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  ViewBox2: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
    alignContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 10,
  },
  flex: {
    flex: 1,
  },
  ViewBox1: {
    width: Dimensions.get('window').width * 0.93,
    height: null,
    backgroundColor: '#FFFFFF',
    alignSelf: 'center',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    marginBottom: 10,
    paddingBottom: 10,
  },
  ViewBox3: {
    width: Dimensions.get('window').width * 0.93,
    height: null,
    backgroundColor: '#FFFFFF',
    alignSelf: 'center',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    marginBottom: 10,
    paddingBottom: 10,
  },
  ViewBox4: {
    width: Dimensions.get('window').width * 0.93,
    height: null,
    backgroundColor: '#FFFFFF',
    alignSelf: 'center',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  Line: {
    borderWidth: 0.5,
    borderColor: '#e2e2e2',
    margin: 10,
  },
  smallIcon: {
    marginHorizontal: 10,
    alignItems: 'center',
  },
  ViewIcon: {
    flexDirection: 'row',
    flex: 0.5,
  },
  IconUser: {
    marginLeft: 10,
    color: '#5D6D7E',
  },
  IconUser2: {
    color: '#5D6D7E',
  },
  textUser: {
    fontSize: 22,
    color: '#4b4b4b',
  },
  textDetail: {
    fontSize: 20,
    color: '#4b4b4b',
    marginBottom: 15,
  },
  headerContainer: {
    width: Dimensions.get('window').width * 0.85,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
  },
  headerText: {
    flex: 1,
    fontSize: 22,
    color: '#20416e',
    textAlign: 'center',
  },
  headerGradient: {
    width: Dimensions.get('window').width * 0.93,
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    marginTop: 10,
    padding: 10,
    borderRadius: 10,
  },
  headerGradientText: {
    flex: 1,
    fontSize: 22,
    color: '#fff',
  },
  headerGradientIcon: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  bodyContainer2: {
    width: Dimensions.get('window').width * 0.93,
    justifyContent: 'center',
    alignSelf: 'center',
    // padding: 15,
    // borderBottomLeftRadius: 8,
    // borderBottomRightRadius: 8,
    // backgroundColor: '#FFFFFF',
  },
  bodyContainer: {
    // width: Dimensions.get('window').width * 0.93,
    justifyContent: 'center',
    alignSelf: 'center',
    // padding: 15,
    paddingTop: 12,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  insertFileButton: {
    justifyContent: 'center',
    marginLeft: 10,
  },
  insertInput: {
    flex: 1,
    height: 36,
    justifyContent: 'center',
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 21.5,
    borderColor: '#cad8e1',
    backgroundColor: '#FFFFFF',

    shadowColor: '#cad8e1',
    shadowOffset: {
      height: 0,
      width: 9,
    },
    shadowRadius: 4,
    shadowOpacity: 0.4,
  },
  insertListItem: {
    flex: 1,
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#f3f3f3',
  },
  insertListFileName: {
    flex: 1,
    fontSize: 22,
    marginLeft: 10,
    color: '#4b4b4b',
  },
  redTextHeader: {
    width: Dimensions.get('window').width * 0.93,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  redText: {
    color: '#fe2c2c',
    fontSize: 22,
    flex: 1,
  },
  detailHeadLabel: {
    flex: 0.7,
    fontSize: 22,
    color: '#20416e',
    marginLeft: 10,
  },
  detailLabel: {
    flex: 1,
    marginRight: 10,
  },
  detailContainer: {
    // flex: 1,
    width: Dimensions.get('window').width * 0.93,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  alertContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    width: '95%',
    marginBottom: 15,
  },
  marginBottom10: {
    marginBottom: 10,
  },
  child: {
    width: width - 20,
    // justifyContent: 'center',
    // alignItems: 'center',
    // backgroundColor: '#9DD6EB',
  },
  // slide2: {
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   backgroundColor: '#97CAE5',
  // },
  // slide3: {
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   backgroundColor: '#92BBD9',
  // },
  wrapper: {
    // flex: 1,
    // width: '100%',
    // backgroundColor: '#000000',
  },
  opacityBTN: {
    opacity: 0.5,
  },
  dropdownIcon2: {
    marginRight: 20,
    top: Platform.OS === 'android' ? 16 : 3,
    left: 10
  },
});
