import {StyleSheet, Dimensions} from 'react-native';
import {ViewScale} from '../../config/ViewScale'
const {width, height} = Dimensions.get('window');
export default StyleSheet.create({
  Searchcss: {
    marginTop: ViewScale(25),
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: ViewScale(20),
    borderWidth: 1,
    borderColor: '#999999',
    borderRadius: ViewScale(18),
    height: ViewScale(33),
  },
  IconSearchcss: {
    width: ViewScale(25),
    height: ViewScale(25),
    backgroundColor: 'transparent',
    marginLeft: ViewScale(10),
    marginTop: ViewScale(5),
  },
  TextInputSearchcss: {
    fontSize: ViewScale(20),
    color: '#000000',
    marginLeft: ViewScale(10),
    backgroundColor: 'transparent',
    padding: ViewScale(0),
    height: '100%',
    width: '100%',
    flex: 1,
    paddingRight: ViewScale(10),
  },
  textmeenustory: {
    textAlign: 'center',
    fontSize: ViewScale(22),
    color: '#FFFFFF',
    fontFamily: 'Kittithada Bold 75',
  },
  textmeenustory2: {
    textAlign: 'center',
    fontSize: ViewScale(22),
    color: '#2d6dc4',
    fontFamily: 'Kittithada Bold 75',
  },
  viewtab: {
    borderWidth: 1,
    flexDirection: 'row',
    borderColor: '#3986ee',
    marginTop: ViewScale(20),
  },
  tabAll: {
    flex: 0.7,
    height: ViewScale(42),
    justifyContent: 'center',
    borderWidth: 0.8,
    borderColor: '#3986ee',
  },
  fontEnd: {
    fontSize: ViewScale(18),
    color: '#ffffff',
  },
  viewEnd: {
    width: ViewScale(104),
    height: ViewScale(28),
    backgroundColor: '#2d6dc4',
    borderRadius: ViewScale(8),
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    alignContent: 'center',
    marginVertical: ViewScale(10),
  },
  viewFootEnd: {
    height: ViewScale(50),
  },
  viewMainAlert: {height: ViewScale(300), alignItems: 'center'},
  alerttitle: {alignItems: 'center', marginTop: ViewScale(10), width: '60%'},
  fontalertitle: {fontSize: ViewScale(22), color: '#163c70', textAlign: 'center'},
  background2d6c480: {backgroundColor: '#2d6dc480'},
  viewImagealert1: {
    flex: 0.8,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: ViewScale(25),
  },
  viewAlert2: {
    width: '30%',
    alignItems: 'center',
  },
  sizeImageAlert: {
    width: ViewScale(50),
    height: ViewScale(47),
  },
  colorTextAlert: {
    fontSize: ViewScale(20),
    color: '#4d4d4d',
  },
  colorTextAlert2: {fontSize: ViewScale(20), color: '#dcdcdc'},
  viewTextCenterAlert: {
    width: '90%',
    marginTop: ViewScale(10),
  },
  textCenterAlert: {textAlign: 'center', color: '#4d4d4d', fontSize: ViewScale(20)},
  marginTop20: {marginTop: ViewScale(20)},
  btnAlert: {
    width: ViewScale(220),
    height: ViewScale(45),
    borderRadius: ViewScale(24.5),
    backgroundColor: '#002270',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textBTNAlert: {fontSize: ViewScale(22), color: '#ffffff'},
  viewMainInput: {
    flexDirection: 'row',
    width: '100%',
    height: ViewScale(57),
    backgroundColor: '#ffffff',
    shadowOffset: {width: 1, height: -3},
    shadowColor: '#cccccc',
    shadowOpacity: 0.1,
  },
  viewLeftInput: {
    width: '25%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  imageFile: {width: ViewScale(15), resizeMode: 'contain'},
  imagePhoto: {width: ViewScale(20), resizeMode: 'contain'},
  viewCenterInput: {
    width: width*0.5,
    height: null,
    // marginHorizontal: 8,
    marginTop: ViewScale(13),
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: ViewScale(21),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3.84,
    elevation: 2,
  },
  inputChat: {
    // width: '70%',
    // marginLeft: 15,
    // height: 50,
    fontFamily: 'PSL Kittithada Pro',
    fontWeight: 'normal',
    color: '#000000',
    fontSize: ViewScale(25),
    // borderWidth:1,
    flex:1,
    // paddingTop: 10,
  },
  viewBTNChat: {
    // marginTop:13,
    width: ViewScale(60),
    height: ViewScale(26),
    marginHorizontal: ViewScale(5),
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#04a68a',
    borderRadius: ViewScale(40),
    position: 'absolute',
    right: ViewScale(0),
    alignItems: 'center',
  },
  textBtnInput: {
    fontSize: ViewScale(18),
    color: '#ffffff',
    fontFamily: 'PSL Kittithada Pro',
  },
  chatWrap: {
    width,
    height,
    backgroundColor: '#ffffff',
  },
  onlineIndicator: {
    fontSize: ViewScale(20),
    color: 'green',
  },
  subtitleWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  mapView: {
    width: ViewScale(150),
    height: ViewScale(100),
    borderRadius: ViewScale(13),
    margin: ViewScale(3),
  },
  viewMainBotChat: {
    width: ViewScale(269),
    zIndex: -1,
  },
  textTitleBotChat: {
    color: '#4d4d4d',
    fontSize: ViewScale(18),
    margin: ViewScale(10),
    fontFamily: 'PSL Kittithada Pro',
  },
  listItemBotChat: {
    marginHorizontal: ViewScale(3),
    marginTop: ViewScale(3),
  },
  textBotChat: {
    color: '#2d6dc4',
    fontSize: ViewScale(18),
  },
  textBottomBotChat: {
    color: '#4d4d4d',
    fontSize: ViewScale(18),
    margin: ViewScale(10),
    fontFamily: 'PSL Kittithada Pro',
  },
  lineChat: {
    width: '90%',
    height: ViewScale(1),
    backgroundColor: '#97979750',
    marginVertical: ViewScale(15),
    alignSelf: 'center',
  },
  color246dc4: {
    color: '#2d6dc4',
  },
  hashtag: {
    color: '#2d6dc4',
  },
});
